packages:
  - ./
  - ./playground
  - ./docs
  - ./examples/*

ignoredBuiltDependencies:
  - sharp

onlyBuiltDependencies:
  - better-sqlite3

patchedDependencies:
  markdown-it-mdc: patches/markdown-it-mdc.patch
